import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useAccount, usePrepareContractWrite, useContractWrite } from 'wagmi';
import { useState, useEffect, useRef, useLayoutEffect } from 'react';
import {
  Flex, Avatar, Text, Box, VStack, Kbd, Link, Accordion, AccordionItem, AccordionButton,
  AccordionPanel, AccordionIcon, Spacer, RadioGroup, Stack, Radio, Button, Center, Progress
} from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'

import { getMaker, getCompound, getAll } from '../resources/getProposals'
import { useContractRead } from 'wagmi'
import contractAbi from '../resources/abi.json'

const Home: NextPage = () => {
  //see if wallet is connected
  const { isConnected } = useAccount()

  //width of progress bar
  const ref = useRef<any>(null);
  const width = 80
  const [barW, setBarW] = useState(0);

  useLayoutEffect(() => {
    setBarW(ref.current.offsetWidth * 0.4);
  }, []);


  //get date progress bar length
  function barLength(start: Date, end: Date) {

    var today = new Date();
    var startDate = new Date(start)
    var endDate = new Date(end)

    const s = startDate.getTime()
    const e = endDate.getTime()
    const c = today.getTime()

    return 100 * (c - s) / (e - s)
  }

  //create function to generate DAO icon
  function getIcon(platform: String) {
    let link
    switch (platform) {
      case "Aave":
        link = "https://cryptologos.cc/logos/aave-aave-logo.png"
        break
      case "Uniswap":
        link = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Uniswap_Logo.svg/1026px-Uniswap_Logo.svg.png"
        break
      case "Compound":
        link = "https://cryptologos.cc/logos/compound-comp-logo.png"
        break
      case "Maker":
        link = "https://seeklogo.com/images/M/maker-mkr-logo-FAA728D102-seeklogo.com.png"
        break
    }
    return link
  }
  function getColor(platform: String) {
    let color
    switch (platform) {
      case "Maker":
        color = "#1AAB9B"
        break
      case "Compound":
        color = "#00D395"
        break
    }
    return color
  }
  function getIdsFromPlatforms(maker: [], compound: []) {
    let lst: [] = []
    for (const x of maker) {
      lst.push(x.id);
    }
    for (const x of compound) {
      lst.push(x.id);
    }
    return lst
  }
  //get proposals on page load
  const [proposals, setProposals] = useState<any>({})
  const [isLoading, setLoading] = useState(false)
  const [ids, setIds] = useState([])
  useEffect(() => {
    setLoading(true)
    getMaker()
      .then((mkr) => {
        getCompound()
          .then((cmp) => {
            setProposals({ "MakerDAO": mkr, "Compound": cmp })
            //get all proposal IDS
            let lst = getIdsFromPlatforms(mkr, cmp)
            setIds(lst)
            setLoading(false)
          })
      })
  }, [])


  const [proposalVotes, setProposalVotes] = useState<any>()
  const contractRead = useContractRead({
    address: '0xe5fB82e33729091c2C62B2a015f808a5f808E153',
    abi: contractAbi,
    functionName: 'proposals',
    args: ["30"]
  })
  const prop30 = contractRead.data
  
  //make vote
  const [vote30Choice, setVote30Choice] = useState(false)
  const { address, isConnecting, isDisconnected } = useAccount()
  console.log(address)
  const {voteConfig} = usePrepareContractWrite({
    address: "0xe5fB82e33729091c2C62B2a015f808a5f808E153",
    abi: contractAbi,
    functionName: "submitMemberVote",
    args: ["30", "1", address, 0, "1234"],
    onError(error) {
      console.log('Error', error)
    },
    onSettled(data, error) {
      console.log('Settled', { data, error })
    },

  })

  const { voteData, voteIsLoading, voteIsSuccess, voteWrite } = useContractWrite(voteConfig)

  if (isLoading) return <p>Loading...</p>
  if (!proposals) return <p>No Active Proposals!</p>

  return (
    <div className={styles.container}>
      <Head>
        <title>GoatVoter</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ConnectButton />
        <Box width={width + "%"} ref={ref}>
          {
            Object.keys(proposals).map((key: any, index: any) =>
              <Accordion allowMultiple>
                {/* {Object.keys(proposals).map((key, index) => {}} */}
                <AccordionItem>
                  <h2>
                    <AccordionButton>
                      <Box flex='1' textAlign='left'>
                        {key}
                      </Box>
                      <AccordionIcon />
                    </AccordionButton>

                  </h2>
                  <AccordionPanel>
                    <VStack align='stretch'>
                      {
                        proposals[key]
                          .map((prop: any) =>
                            <Flex key={prop.id} paddingY={3}>
                              <Center>
                                <Avatar src={getIcon(prop.platform)} />
                                <Box ml='3' key={prop.id}>
                                  {/* <Text fontWeight='bold'>
                              {prop.platform} - <Kbd><Link href={prop.pollForum} isExternal>See More<ExternalLinkIcon mx='2px' /></Link></Kbd>
                            </Text> */}
                            
                                  <Text fontWeight='bold'>{prop.title} <Kbd><Link href={prop.link} isExternal><ExternalLinkIcon mx='2px' /></Link></Kbd></Text>
                                  <Progress width={barW} value={barLength(prop.startDate, prop.endDate)} colorScheme='green' />
                                  {prop.id != 30 && isConnected && <Text>Member Votes: Yay: {0}, Nay: {0}</Text>}
                                  {prop.id == 30 &&isConnected && <Text>Member Votes: Yay: {parseInt(prop30["yea"]._hex, 16)}, Nay: {parseInt(prop30["nay"]._hex, 16)}</Text>}
                                </Box>
                              </Center>
                              <Spacer />
                              <Center>
                                <Flex>
                                  <RadioGroup>
                                    <Stack spacing={5} direction='row'>
                                      <Radio colorScheme='green' value='1' onClick={() => {setVote30Choice(true)}}>
                                        Yay
                                      </Radio>
                                      <Radio colorScheme='red' value='2' onClick={() => {setVote30Choice(false)}}>
                                        Nay
                                      </Radio>
                                      {prop.id == 30 &&
                                        <Button colorScheme='teal' size='xs' onClick={voteWrite?.()}>
                                          Submit
                                        </Button>
                                      }
                                      {prop.id != 30 &&
                                        <Button colorScheme='green' size='xs'>
                                          Submit
                                        </Button>
                                      }
                                    </Stack>
                                  </RadioGroup>
                                </Flex>
                              </Center>
                            </Flex>

                          )
                      }
                    </VStack>
                  </AccordionPanel>

                </AccordionItem>

              </Accordion>
            )}
        </Box>
      </main>

    </div>
  );
};

export default Home;
